openai_api_key: "YOUR_OPENAI_API_KEY"
groq_api_key: "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"
telegram_token: "YOUR_TELEGRAM_TOKEN"
telegram_chat_id: "YOUR_CHAT_ID"
rss_feed_url: "https://www.moneycontrol.com/rss/markets.xml"
kite_api_key: "s5clm4cvdoidnpbt"
kite_access_token: "YOUR_KITE_ACCESS_TOKEN"
kite_api_secret: "zrinp2au5txiq0bgs6sggxsg95ajtnzh"
kite_redirect_uri: "https://172.232.119.157:8080/api/auth/callback"
# user-provided application name for reference
kite_app_name: "backtester"
# default investment amount by confidence score 1-10
confidence_investment:
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
  6: 0
  7: 0
  8: 0
  9: 0
  10: 0
